"use strict";
module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily: '"JetBrainsMono Nerd Font", Monaco, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: '600',
    fontWeightBold: '900',
    lineHeight: 1.2,
    letterSpacing: 1.04,
    cursorColor: '#ab4642',
    cursorAccentColor: '#181818',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#d8d8d8',
    backgroundColor: '#181818',
    selectionColor: '#585858',
    borderColor: '#a1b56c',
    css: '',
    termCSS: '',
    workingDirectory: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '8px 8px 8px 8px',
    colors: {
      black: "#181818",
      blue: "#7cafc2",
      red: "#ab4642",
      green: "#a1b56c",
      yellow: "#f7ca88",
      magenta: "#ba8baf",
      cyan: "#86c1b9",
      white: "#d8d8d8",
      lightBlack: "#585858",
      lightWhite: "#f8f8f8",
      lightBlue: "#7cafc2",
      lightRed: "#ab4642",
      lightGreen: "#a1b56c",
      lightYellow: "#f7ca88",
      lightMagenta: "#ba8baf",
      lightCyan: "#86c1b9",
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    webLinksActivationKey: '',
    disableLigatures: false,
    disableAutoUpdates: true,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {
  },
};
