#!/usr/bin/env sh

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xffcba6f7,bottom_right=0xff89b4fa)"
  inactive_color="gradient(top_left=0xff9399b2,bottom_right=0xff585b70)"
  background_color=0xff181818
)
borders "${options[@]}"
