#!/usr/bin/env sh

# General
ROSEWATER="0xfff2cdcd"
FLAMINGO="0xfff5c2e7"
PINK="0xfff5c2e7"
MAUVE="0xffcba6f7"
RED="0xfff38ba8"
MAROON="0xffeba0ac"
PEACH="0xfffab387"
YELLOW="0xfff9e2af"
GREEN="0xffa6e3a1"
TEAL="0xff94e2d5"
SKY="0xff89dceb"
SAPPHIRE="0xff74c7ec"
BLUE="0xff89b4fa"
LAVENDER="0xffb4befe"
TEXT="0xffcdd6f4"
SUBTEXT1="0xffbac2de"
SUBTEXT0="0xffa6adc8"
OVERLAY2="0xff9399b2"
OVERLAY1="0xff7f849c"
OVERLAY0="0xff6c7086"
SURFACE2="0xff585b70"
SURFACE1="0xff45475a"
SURFACE0="0xff313244"
BASE="0xff1e1e2e"
MANTLE="0xff181825"
CRUST="0xff11111b"

BAR=(
  potision=top
  height=30
  color=$CRUST
  shadow=off
  stiky=on
  padding_right=6
  padding_left=6
  margin=0
)
sketchybar --bar "${BAR[@]}"

DEFAULT=(
  updates=when_shown
  icon.font="SF Pro:Bold:13.0"
  icon.color=$SUBTEXT1
  icon.padding_left=3
  icon.padding_right=3
  label.font="SF Pro:Semibold:12.0"
  label.color=$SUBTEXT1
  label.padding_left=3
  label.padding_right=3
  padding_left=3
  padding_right=3
  background_height=24
  background.corner_radius=6
  background.border_width=1
  popup.background.border_width=3
  popup.background.corner_radius=6
  popup.background.border_color=$MANTLE
  popup.background.color=$MANTLE
  popup.blur_radius=24
  popup.background.shadow.drawing=on
)
sketchybar --default "${DEFAULT[@]}"

# Left

# APPLE LOGO
APPLE_LOGO=(
  icon=􀣺
  icon.font="SF Pro:Bold:16.0"
  icon.color=$GREEN
  icon.padding_left=9
  icon.padding_right=9
  padding_right=9
  label.drawing=off
  background.color=$BASE
  background.border_color=$SURFACE1
  popup.height=30
  click_script="sketchybar --set \$NAME popup.drawing=toggle"
)
sketchybar --add item apple.logo left --set apple.logo "${APPLE_LOGO[@]}"

PREFERENCE=(
  icon=􀺽
  label="System Preferences"
  click_script="open -a 'System Preferences'; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.preference popup.apple.logo --set apple.preference "${PREFERENCE[@]}"

ACTIVITY=(
  icon=􀒓
  label="Activity Monitor"
  click_script="open -a 'Activity Monitor'; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.activity popup.apple.logo --set apple.activity "${ACTIVITY[@]}"

LOCK=(
  icon=􀒳
  label="Lock Screen"
  click_script="pmset displaysleepnow; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.lock popup.apple.logo --set apple.lock "${LOCK[@]}"

# WORKSPACE
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  SPACE=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=9
    icon.padding_right=9
    padding_left=3
    padding_right=3
    label.drawing=off
    background.color=$BASE
    background.border_color=$SURFACE1
    click_script="yabai -m space --focus $sid"
    script="
      if [[ \"\$SELECTED\" == \"true\" ]]; then
        sketchybar --set \"\$NAME\" background.drawing=\"\$SELECTED\" icon.color=$RED
      else
        sketchybar --set \"\$NAME\" background.drawing=\"\$SELECTED\" icon.color=$SURFACE2
      fi
    "
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${SPACE[@]}" --subscribe space.$sid mouse.clicked
done

# SEPARATOR
SEPARATOR=(
  icon=􀆊
  icon.color=$ROSEWATER
  padding_left=9
  padding_right=9
  label.drawing=off
  display=active
  click_script='yabai -m space --create'
)
sketchybar --add item separator left --set separator "${SEPARATOR[@]}" --subscribe separator space_window_change

# WINDOW TITLE
WINDOW_TITLE=(
  icon.drawing=off
  label.font="SF Pro:Black:12.0"
  display=active
  background.color=$BASE
  background.border_color=$SURFACE1
  label.padding_left=9
  label.padding_right=9
  click_script="open -a 'Mission Control'"
  script='
    if [ "$SENDER" = "front_app_switched" ]; then
      sketchybar --set "$NAME" label="$INFO"
    fi
  '
)
sketchybar --add item window_title left --set window_title "${WINDOW_TITLE[@]}" --subscribe window_title front_app_switched

# RIGHT

# DATETIME
DATETIME=(
  icon=􀧞
  update_freq=10
  background.color=$BASE
  background.border_color=$SURFACE1
  icon.padding_left=9
  label.padding_right=9
  script="
    sketchybar --set \"\$NAME\" label=\"\$(date '+%Y-%m-%d %H:%M')\"
  "
)
sketchybar --add item datetime right --set datetime "${DATETIME[@]}"

# BATTERY
BATTERY=(
  background.color=$BASE
  background.border_color=$SURFACE1
  icon.padding_left=9
  label.padding_right=9
  update_freq=120
  script="
    PERCENTAGE=\"\$(pmset -g batt | grep -Eo \"\d+%\" | cut -d% -f1)\"
    CHARGING=\"\$(pmset -g batt | grep 'AC Power')\"
    if [ -z \"\$PERCENTAGE\" ]; then
      exit 0
    fi
    case \"\$PERCENTAGE\" in
      9[0-9]|100)
        ICON=\"􀛨\"
        COLOR=$GREEN
        ;;
      [6-8][0-9])
        ICON=\"􀺸\"
        COLOR=$YELLOW
        ;;
      [3-5][0-9])
        ICON=\"􀺶\"
        COLOR=$PEACH
        ;;
      [1-2][0-9])
        ICON=\"􀛩\"
        COLOR=$MAROON
        ;;
      *)
        ICON=\"􀛪\"
        COLOR=$RED
        ;;
    esac
    if [[ -n \"\$CHARGING\" ]]; then
      ICON=\"􀢋\"
      COLOR=$TEAL
    fi
    sketchybar --set \"\$NAME\" icon=\"\$ICON\" label=\"\${PERCENTAGE}%\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item battery right --set battery "${BATTERY[@]}" --subscribe battery system_woke power_source_change

# VOLUME
VOLUME=(
  icon.padding_left=9
  label.padding_right=9
  background.color=$BASE
  background.border_color=$SURFACE1
  script="
    if [ \"\$SENDER\" = \"volume_change\" ]; then
      VOL=\"\$INFO\"
      case \"\$VOL\" in
      [8-9][0-9]|100)
        ICON=\"􀊩\"
        COLOR=$RED
        ;;
      [5-8][0-9])
        ICON=\"􀊧\"
        COLOR=$PEACH
        ;;
      [3-5][0-9])
        ICON=\"􀊥\"
        COLOR=$YELLOW
        ;;
      [1-9]|[1-3][0-9])
        ICON=\"􀊥\"
        COLOR=$GREEN
        ;;
      *)
        ICON=\"􀊣\"
        COLOR=$RED
        ;;
      esac
      sketchybar --set \"\$NAME\" icon=\"\$ICON\" icon.color=\"\$COLOR\" label=\"\$VOL%\"
    fi
  "
)
sketchybar --add -item volume right --set volume "${VOLUME[@]}" --subscribe volume volume_change

# RAM
RAM=(
  icon.padding_left=9
  label.padding_right=9
  background.color=$BASE
  background.border_color=$SURFACE1
  update_freq=3
  script="
    TOTAL_RAM_BYTES=\$(sysctl -n hw.memsize)
    PAGE_SIZE=\$(sysctl -n vm.pagesize)
    read FREE_PAGES INACTIVE_PAGES SPECULATIVE_PAGES <<< \$(vm_stat | awk \\
        '/Pages free/ {free=\$3} \\
         /Pages inactive/ {inactive=\$3} \\
         /Pages speculative/ {speculative=\$3} \\
         END {print free, inactive, speculative}' | tr -d '.')
    NON_ACTIVE_PAGES=\$((FREE_PAGES + INACTIVE_PAGES + SPECULATIVE_PAGES))
    NON_ACTIVE_RAM_BYTES=\$((NON_ACTIVE_PAGES * PAGE_SIZE))
    USED_RAM_BYTES=\$((TOTAL_RAM_BYTES - NON_ACTIVE_RAM_BYTES))
    if [ \$TOTAL_RAM_BYTES -gt 0 ]; then
      RAM_PERCENTAGE=\$((USED_RAM_BYTES * 100 / TOTAL_RAM_BYTES))
      if [ \$RAM_PERCENTAGE -lt 0 ]; then
        RAM_PERCENTAGE=0
      elif [ \$RAM_PERCENTAGE -gt 100 ]; then
        RAM_PERCENTAGE=100
      fi
    else
      RAM_PERCENTAGE=0
    fi
    case \"\$RAM_PERCENTAGE\" in
      9[0-9]|100)
        ICON=􀐟
        COLOR=$RED
        ;;
      [6-8][0-9])
        ICON=􀐟
        COLOR=$PEACH
        ;;
      [3-5][0-9])
        ICON=􀐞
        COLOR=$YELLOW
        ;;
      *)
        ICON=􀐞
        COLOR=$GREEN
        ;;
    esac
    sketchybar --set \"\$NAME\" label=\"\$RAM_PERCENTAGE%\" icon=\"\$ICON\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item ram right --set ram "${RAM[@]}"

# CPU
CPU=(
  icon.padding_left=9
  label.padding_right=9
  background.color=$BASE
  background.border_color=$SURFACE1
  update_freq=3
  script="
    CPU_PERCENTAGE=\$(top -l 2 | grep -E \"^CPU\" | tail -1 | awk '{ printf(\"%d\", \$3 + \$5) }')
    case \"\$CPU_PERCENTAGE\" in
      9[0-9]|100)
        ICON=􀧓
        COLOR=$RED
        ;;
      [6-8][0-9])
        ICON=􀧓
        COLOR=$PEACH
        ;;
      [3-5][0-9])
        ICON=􀫥
        COLOR=$YELLOW
        ;;
      *)
        ICON=􀫥
        COLOR=$GREEN
        ;;
    esac
    sketchybar --set \$NAME label=\"\$CPU_PERCENTAGE%\" icon=\"\$ICON\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item cpu right --set cpu "${CPU[@]}"

sketchybar --update
