"use strict";
module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily: '"JetBrainsMono Nerd Font", Monaco, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: '600',
    fontWeightBold: '900',
    lineHeight: 1.2,
    letterSpacing: 1.04,
    cursorColor: '#f38ba8',
    cursorAccentColor: '#11111b',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#cdd6f4',
    backgroundColor: '#11111b',
    selectionColor: '#45475a',
    borderColor: '#f5e0dc',
    css: '',
    termCSS: '',
    workingDirectory: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '8px 8px 8px 8px',
    colors: {
      black: "#11111b",
      blue: "#89b4fa",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      magenta: "#cba6f7",
      cyan: "#89dceb",
      white: "#cdd6f4",
      lightBlack: "#1e1e2e",
      lightWhite: "#cdd6f4",
      lightBlue: "#89b4fa",
      lightRed: "#f38ba8",
      lightGreen: "#a6e3a1",
      lightYellow: "#f9e2af",
      lightMagenta: "#cba6f7",
      lightCyan: "#89dceb",
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    webLinksActivationKey: '',
    disableLigatures: false,
    disableAutoUpdates: true,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {
  },
};
